const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS'
const LOAD_PHOTOS_START = 'LOAD_PHOTOS_START'
const CLEAR_PHOTOS_STATE = 'CLEAR_PHOTOS_STATE'

const types = {
  LOAD_PHOTOS_START,
  LOAD_PHOTOS_SUCCESS,
  CLEAR_PHOTOS_STATE
}

export default types;