const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const CHANGE_USERNAME = 'CHANGE_USERNAME';
const CLEAR_USER = 'CLEAR_USER';
const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
const SET_NOTIFICATIONS_LOADING = 'SET_NOTIFICATIONS_LOADING';

const types = {
  GET_USER_SUCCESS,
  CHANGE_USERNAME,
  CLEAR_USER,
  SET_NOTIFICATIONS,
  SET_NOTIFICATIONS_LOADING
}

export default types;